Switch to Julia v1.12
We're getting some errors on v1.11:

```
ERROR: LoadError: MethodError: no method matching abspath(::Nothing)
The function `abspath` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  abspath(::String)
   @ Base path.jl:448
  abspath(::AbstractString)
   @ Base path.jl:614
  abspath(::AbstractString, AbstractString...)
   @ Base path.jl:468

Stacktrace:
  [1] fixup_ext!(env::Pkg.Types.EnvCache)
    @ Pkg.Operations ~/actions-runner/_work/_tool/julia/1.11.6/x64/share/julia/stdlib/v1.11/Pkg/src/Operations.jl:185
  [2] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, new_git::Set{Base.UUID}; allow_autoprecomp::Bool, preserve::Pkg.Types.PreserveLevel, platform::Platform, target::Symbol)
    @ Pkg.Operations ~/actions-runner/_work/_tool/julia/1.11.6/x64/share/julia/stdlib/v1.11/Pkg/src/Operations.jl:1449
  [3] add
    @ ~/actions-runner/_work/_tool/julia/1.11.6/x64/share/julia/stdlib/v1.11/Pkg/src/Operations.jl:1418 [inlined]
  [4] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Platform, target::Symbol, allow_autoprecomp::Bool, kwargs::@Kwargs{julia_version::Nothing, io::IOContext{Base.PipeEndpoint}})
    @ Pkg.API ~/actions-runner/_work/_tool/julia/1.11.6/x64/share/julia/stdlib/v1.11/Pkg/src/API.jl:312
  [5] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::IOContext{Base.PipeEndpoint}, kwargs::@Kwargs{platform::Platform, julia_version::Nothing})
    @ Pkg.API ~/actions-runner/_work/_tool/julia/1.11.6/x64/share/julia/stdlib/v1.11/Pkg/src/API.jl:159
  [6] add
    @ ~/actions-runner/_work/_tool/julia/1.11.6/x64/share/julia/stdlib/v1.11/Pkg/src/API.jl:148 [inlined]
  [7] (::BinaryBuilderBase.var"#94#95"{@Kwargs{platform::Platform, io::IOContext{Base.PipeEndpoint}, julia_version::Nothing}, Tuple{Vector{Pkg.Types.PackageSpec}}})()
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/dNGD5/src/Prefix.jl:696
  [8] withenv(f::BinaryBuilderBase.var"#94#95"{@Kwargs{platform::Platform, io::IOContext{Base.PipeEndpoint}, julia_version::Nothing}, Tuple{Vector{Pkg.Types.PackageSpec}}}, keyvals::Pair{String, String})
    @ Base ./env.jl:265
  [9] #Pkg_add#93
    @ ~/.julia/packages/BinaryBuilderBase/dNGD5/src/Prefix.jl:690 [inlined]
 [10] (::BinaryBuilderBase.var"#97#105"{Bool, Prefix, Vector{Pkg.Types.PackageSpec}, Platform, Vector{String}, Vector{String}})()
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/dNGD5/src/Prefix.jl:770
 [11] activate(f::BinaryBuilderBase.var"#97#105"{Bool, Prefix, Vector{Pkg.Types.PackageSpec}, Platform, Vector{String}, Vector{String}}, new_project::String)
    @ Pkg.API ~/actions-runner/_work/_tool/julia/1.11.6/x64/share/julia/stdlib/v1.11/Pkg/src/API.jl:1379
 [12] setup_dependencies(prefix::Prefix, dependencies::Vector{Pkg.Types.PackageSpec}, platform::Platform; verbose::Bool)
    @ BinaryBuilderBase ~/.julia/packages/BinaryBuilderBase/dNGD5/src/Prefix.jl:762
 [13] setup_dependencies
    @ ~/.julia/packages/BinaryBuilderBase/dNGD5/src/Prefix.jl:726 [inlined]
 [14] (::BinaryBuilder.var"#setup_deps#25")(f::typeof(BinaryBuilderBase.is_target_dependency), prefix::Prefix, dependencies::Vector{BinaryBuilderBase.AbstractDependency}, platform::Platform, verbose::Bool)
    @ BinaryBuilder ~/.julia/packages/BinaryBuilder/yHbT3/src/AutoBuild.jl:866
 [15] autobuild(dir::AbstractString, src_name::AbstractString, src_version::VersionNumber, sources::Vector{<:BinaryBuilderBase.AbstractSource}, script::AbstractString, platforms::Vector, products::Vector{<:Product}, dependencies::Vector{<:BinaryBuilderBase.AbstractDependency}; verbose::Bool, debug::Bool, skip_audit::Bool, ignore_audit_errors::Bool, autofix::Bool, code_dir::Union{Nothing, String}, require_license::Bool, dont_dlopen::Bool, compression_format::String, kwargs...)
    @ BinaryBuilder ~/.julia/packages/BinaryBuilder/yHbT3/src/AutoBuild.jl:869
 [16] build_tarballs(ARGS::Any, src_name::Any, src_version::Any, sources::Any, script::Any, platforms::Any, products::Any, dependencies::Any; julia_compat::String, validate_name::Bool, compression_format::String, kwargs...)
    @ BinaryBuilder ~/.julia/packages/BinaryBuilder/yHbT3/src/AutoBuild.jl:380
 [17] top-level scope
    @ ~/actions-runner/_work/ReactantBuilder/ReactantBuilder/R/Reactant/build_tarballs.jl:624
in expression starting at /home/wmoses/actions-runner/_work/ReactantBuilder/ReactantBuilder/R/Reactant/build_tarballs.jl:623
```

Hopefully fixed on v1.12, let's see.